### PR TITLE
Adding LoTerra to the bridge

### PR DESCRIPTION
**Pull request by 0xantman**
Can you guys review this PR and add LoTerra LOTA token to the bridge? Thank you @ouiliame @hanjukim @dokwon

### CODE REVIEW

**Comment by 0xantman** [comment]
Hey! we don't want someone to lose his LOTA on the bridge because LOTA is available to swap on terra bridge...

**Comment by YunSuk-Yeo** [comment]
Hey we will move all our shuttle brigaded assets to wormhole assets, so it will be much better to use wormhole.

btw swap on terra bridge is available?? thanks, we will deactivate that for now and enable wormhole support.

**Comment by YunSuk-Yeo** [comment]
you can refer https://medium.com/terra-money/terra-goes-live-on-wormhole-v2-12df49d446d2

**Comment by 0xantman** [comment]
> you can refer https://medium.com/terra-money/terra-goes-live-on-wormhole-v2-12df49d446d2

Ok Thank you i can close this PR

**Pull request closed without merging**
